{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: simple-services
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}
      port:
        number: {{ .Values.service.port.external }}
  rules:
    - host: {{ .Chart.Name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port.external }}
  {{- end }}