apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: simple-services
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port.external }}
      targetPort: {{ .Values.service.port.container }}