domain: romanow-alex.ru
ingress:
  enabled: false

service:
  port:
    container:
    external:
  enviroments: { }
  image:
    name:
    version:
  resources:
    requests:
      cpu:
      memory:
    limits:
      cpu:
      memory:
  probes:
    liveness:
    readiness:
